language: node_js
node_js: 12.18.3
services: docker
addons:
  apt:
    packages:
      - docker-ce

stages:
  - build
  - publish

branches:
  only:
  - master

jobs:
  include:
    # Check prettier linting and build typescript
    - stage: build
      script:
        - yarn run format:check
        - yarn run build
    # Build and publish docker tags
    - stage: publish
      if: branch == master AND (NOT (type IN (pull_request)))
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
      script:
        # Build dockerfile
        - make build
        # Push tags
        - make push
