version: "3"
services:
  gatsby:
    image: gatsbytv/gatsby:latest
    ports:
      - 3000:3000
    restart: always
    networks:
      - gatsby
    env_file:
      - .env

  westegg:
    build: .
    image: gatsbytv/westegg:latest
    env_file:
      - .env
    ports:
     - 3001:3001
    restart: always
    networks:
      - gatsby

  mongo1:
    image: mongo:4.4.1
    ports:
      - 27017:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    environment:
      MONGO_INITDB_DATABASE: gatsby
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
      MONGO_API_USER: ${MONGO_API_USER}
      MONGO_API_PASS: ${MONGO_API_PASS}
    volumes:
      - ./.db:/data/db
      - ./mongo/init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    networks:
      - gatsby
  mongo2:
    image: mongo:4.4.1
    ports:
      - 27018:27018
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    environment:
      MONGO_INITDB_DATABASE: gatsby
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
      MONGO_API_USER: ${MONGO_API_USER}
      MONGO_API_PASS: ${MONGO_API_PASS}
    volumes:
      - ./.db:/data/db
      - ./mongo/init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    networks:
      - gatsby
  mongo3:
    image: mongo:4.4.1
    ports:
      - 27019:27019
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    environment:
      MONGO_INITDB_DATABASE: gatsby
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
      MONGO_API_USER: ${MONGO_API_USER}
      MONGO_API_PASS: ${MONGO_API_PASS}
    volumes:
      - ./.db:/data/db
      - ./mongo/init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    # ports:
    #   - 27017:27017
    networks:
      - gatsby

  ipfs:
    image: gatsbytv/go-ipfs:v0.8.0
    volumes:
      - ./.ipfs:/data/ipfs
    ports:
      # Swarm TCP
      - 4001:4001
      # Swarm Websockets
      - 8081:8081
      # HTTP Gateway
      - 8080:8080
      # Private Daemon API
      - 127.0.0.1:5001:5001
    networks:
      - gatsby

networks:
  gatsby:
