version: "3"
services:

  # Gatsby frontend
  gatsby:
    image: gatsbytv/gatsby:latest
    ports:
      - 3000:3000
    restart: always
    networks:
      - gatsby

  # Westegg
  westegg:
    build: .
    image: westegg
    environment:
      # API app config
      PORT: 3001
      # Mongo config
      MONGO_PROTOCOL: mongodb
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_API_USER: ${MONGO_API_USER}
      MONGO_API_PASS: ${MONGO_API_PASS}
      MONGO_API_DB: gatsby
      # IPFS config
      IPFS_URL: ${IPFS_URL}
      # Email config
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      # Westegg config
      JWT_SECRET: ${JWT_SECRET}
      LOGGING_LEVEL: ${LOGGING_LEVEL}
      WESTEGG_ENV: ${WESTEGG_ENV}
      PUBLIC_URL: ${PUBLIC_URL}
    ports:
     - 3001:3001
    restart: always
    networks:
      - gatsby

  # Redis
  redis:
    image: redis:6.2.2
    ports:
      - 6379:6379
    networks:
      - gatsby

  # Mongo
  mongo:
    image: mongo:4.4.1
    environment:
      # Root db user
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}
      # API db and user
      - MONGO_INITDB_DATABASE=gatsby
      - MONGO_API_USER=gatsby
      - MONGO_API_PASS=${MONGO_API_PASS}
    volumes:
      - ./.db:/data/db
      - ./mongo/init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports:
      - 27017:27017
    networks:
      - gatsby

  # IPFS
  ipfs:
    image: gatsbytv/go-ipfs:v0.8.0
    volumes:
      - ./.ipfs:/data/ipfs
    ports:
      # Swarm TCP
      - 4001:4001
      # Swarm Websockets
      - 8081:8081
      # HTTP Gateway
      - 8080:8080
      # Daemon API -- DO NOT EXPOSE PUBLICLY
      - 127.0.0.1:5001:5001
    networks:
      - gatsby

networks:
  gatsby:
